/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.awt.print.PrinterException;
import javax.swing.JEditorPane;
import javax.swing.JTextArea;
import javax.swing.table.TableModel;
import java.util.*;

/**
 *
 * @author kobinath
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
     String lsub;
     String lpay;
     String lbal;
private Formatter f = new Formatter(System.out);
    public print() {
        initComponents();
         setUndecorated(true);
    }
         public void printTitle() {
     f.format("%-15s %5s %10s\n", "Item", "Qty", "Price");
      f.format("%-15s %5s %10s\n", "----", "---", "-----");
  }
         
    public void print(String name, int qty, double price) {
     f.format("%-15.15s %5d %10.2f\n", name, qty, price);
    
  }
 public print(String sub,String pay,String bal, TableModel tableModel) throws PrinterException
{
    initComponents();  
  this.lsub = sub;
  this.lpay = pay;
  this.lbal = bal;
  
   

  
  

  for (int i = 0; i < tableModel.getRowCount(); i++)
  {
     String id = (String) tableModel.getValueAt(i,0);
    String product = (String) tableModel.getValueAt(i,1);
    String price = (String) tableModel.getValueAt(i,2);  
    String qty = (String) tableModel.getValueAt(i,3);  
    int total = (int) tableModel.getValueAt(i,4);    
     
   //   jTextArea1.setText(jTextArea1.getText()+ product + "\t"+ price  + "\t" + qty +   "\t" + total +  "\n" );
      
        jTextArea1.setText( String.format("%-15.15s %5d %10.2f\n" + product + "\t"+ price  + "\t" + qty +   "\t" + total +  "\n" ));
      
  }

  //   jTextArea1.print();
  
   
  
 
 
 // txtarea.print();
   
}

    print(int total, TableModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 312, 362));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
